version: '3.8'

services:
  # 1. Banco de Dados Relacional
  kutt_db:
    image: postgres:15-alpine
    container_name: fragata_kutt_db
    environment:
      POSTGRES_USER: kuttuser
      POSTGRES_PASSWORD: encurtadordelinksuperseguro
      POSTGRES_DB: kuttdb
    volumes:
      - kutt_postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. Cache de Alta Performance
  kutt_redis:
    image: redis:7-alpine
    container_name: fragata_kutt_redis
    restart: always

  # 3. A Aplicação Kutt (Node.js/TypeScript)
  kutt:
    image: kutt/kutt:latest
    container_name: fragata_kutt_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DEFAULT_DOMAIN: fragata.me
      DB_CLIENT: pg
      DB_HOST: kutt_db
      DB_USER: kuttuser
      DB_PASSWORD: encurtadordelinksuperseguro
      DB_NAME: kuttdb
      REDIS_HOST: kutt_redis
      JWT_SECRET: 96063d69c6473c1610ae1995e2ace766
      ADMIN_EMAILS: dragonbolad@gmail.com
      REGISTRATION_INVALID_EMAIL: "false"
      DISALLOW_REGISTRATION: "false"
    depends_on:
      - kutt_db
      - kutt_redis
    restart: always

volumes:
  kutt_postgres_data: